CREATE TABLE empresas (cod int(10) NOT NULL AUTO_INCREMENT, razon_social varchar(255) NOT NULL, cod_tipo_identificacion int(10) NOT NULL, numero_identificacion varchar(255) NOT NULL, cod_tercero_representante int(10) NOT NULL, cod_estado_empresa int(10) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE estados_empresas (cod int(10) NOT NULL AUTO_INCREMENT, descripcion varchar(255) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE estados_terceros (cod int(10) NOT NULL AUTO_INCREMENT, descripcion varchar(255) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE estados_usuarios (cod int(10) NOT NULL AUTO_INCREMENT, descripcion varchar(255) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE funciones (cod int(10) NOT NULL AUTO_INCREMENT, descripcion varchar(255) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE funciones_perfiles (cod_funcion int(10) NOT NULL, cod_perfil int(10) NOT NULL, insertar int(10), actualizar int(10), consultar int(10), borrar int(10), PRIMARY KEY (cod_funcion, cod_perfil));
CREATE TABLE paises (cod int(10) NOT NULL AUTO_INCREMENT, pais varchar(40) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE perfiles (cod int(10) NOT NULL AUTO_INCREMENT, descripcion varchar(255) NOT NULL, cod_empresa int(10) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE terceros (cod int(10) NOT NULL AUTO_INCREMENT, razon_social varchar(255) NOT NULL, nombres varchar(120), apellidos varchar(120), fecha_nacimiento date NOT NULL, cod_tipo_identificacion int(10) NOT NULL, numero_identificacion varchar(255) NOT NULL, email varchar(255), telefono varchar(30), celular varchar(30), cod_estado_tercero int(10) NOT NULL, PRIMARY KEY (cod));
CREATE TABLE tipos_identificacion (cod int(10) NOT NULL AUTO_INCREMENT, cod_pais int(10) NOT NULL, descripcion varchar(255) NOT NULL, abreviatura varchar(10), PRIMARY KEY (cod));
CREATE TABLE usuarios (cod int(10) NOT NULL AUTO_INCREMENT, usuario varchar(255) NOT NULL, clave varchar(255) NOT NULL, cod_estado_usuario int(10) NOT NULL, cod_tercero int(10) NOT NULL);
CREATE TABLE usuarios_empresas (cod int(10) NOT NULL AUTO_INCREMENT, cod_empresa int(10) NOT NULL, cod_usuario int(10) NOT NULL, cod_perfil int(10) NULL, PRIMARY KEY (cod));
ALTER TABLE usuarios_empresas ADD CONSTRAINT FKusuarios_e364289 FOREIGN KEY (cod_perfil) REFERENCES perfiles (cod);
ALTER TABLE perfiles ADD CONSTRAINT FKperfiles308178 FOREIGN KEY (cod_empresa) REFERENCES empresas (cod);
ALTER TABLE usuarios_empresas ADD CONSTRAINT FKusuarios_e855523 FOREIGN KEY (cod_usuario) REFERENCES usuarios (cod);
ALTER TABLE usuarios_empresas ADD CONSTRAINT FKusuarios_e78949 FOREIGN KEY (cod_empresa) REFERENCES empresas (cod);
ALTER TABLE empresas ADD CONSTRAINT FKempresas843594 FOREIGN KEY (cod_estado_empresa) REFERENCES estados_empresas (cod);
ALTER TABLE empresas ADD CONSTRAINT FKempresas775441 FOREIGN KEY (cod_tercero_representante) REFERENCES terceros (cod);
ALTER TABLE empresas ADD CONSTRAINT FKempresas58996 FOREIGN KEY (cod_tipo_identificacion) REFERENCES tipos_identificacion (cod);
ALTER TABLE funciones_perfiles ADD CONSTRAINT FKfunciones_552570 FOREIGN KEY (cod_funcion) REFERENCES funciones (cod);
ALTER TABLE funciones_perfiles ADD CONSTRAINT FKfunciones_918042 FOREIGN KEY (cod_perfil) REFERENCES perfiles (cod);
ALTER TABLE terceros ADD CONSTRAINT FKterceros171680 FOREIGN KEY (cod_estado_tercero) REFERENCES estados_terceros (cod);
ALTER TABLE terceros ADD CONSTRAINT FKterceros272541 FOREIGN KEY (cod_tipo_identificacion) REFERENCES tipos_identificacion (cod);
ALTER TABLE tipos_identificacion ADD CONSTRAINT FKtipos_iden908972 FOREIGN KEY (cod_pais) REFERENCES paises (cod);
ALTER TABLE usuarios ADD CONSTRAINT FKusuarios85725 FOREIGN KEY (cod_tercero) REFERENCES terceros (cod);
ALTER TABLE usuarios ADD CONSTRAINT FKusuarios997156 FOREIGN KEY (cod_estado_usuario) REFERENCES estados_usuarios (cod);
